### PR TITLE
fix: #21 and #22, addressing the use of deprecated functions.

### PR DESCRIPTION
**Pull request by Dreznel**
As specified in the associated issues, I switched out ergm::remove.offset.formula() for statnet.common::filter_rhs.formula(). I left the arguments untouched.

Additionally, I removed two deprecated functions from the NAMESPACE file after finding no references to those functions in the code.

Four unit tests, which were failing before I made any changes, are still failing.

### CODE REVIEW

**Comment by leifeld** [comment]
Shouldn't `remove.offset.formula` also be removed from the namespace file?

**Comment by Dreznel** [comment]
> Shouldn't `remove.offset.formula` also be removed from the namespace file?

You are correct, though that one didn't show up from `devtools::check()` that I recall. I'll include that in my next commit.

**Comment by Dreznel** [comment]
I'm having to split my attention a bit today, so let me just jot down my findings so far.

At this point in time, two unit tests remain failing. It would seem that reverting to `ergm` version 3.10.4 causes the unit tests to pass as written. Since `ergm` version 3.11.0 is what's current on CRAN (as of October 14th, 2020), though, we'll need to decide if the changed behavior is still valid.

Here is a screenshot of the test output:
image

```
✓ |  OK F W S | Context
x |  51 2     | test btergm estimation [11.0 s]
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test-btergm.R:148: failure: mtergm estimation works
round(unname(coef(fit2)), 4) not equal to c(-1.1818, 0.0577, 0.0048).
3/3 mismatches (average diff: 0.0021)
[1] -1.1779 - -1.1818 ==  0.0039
[2]  0.0566 -  0.0577 == -0.0011
[3]  0.0035 -  0.0048 == -0.0013

test-btergm.R:149: failure: mtergm estimation works
unname(round(fit2@se, 4)) not equal to c(0.1871, 0.0801, 0.0758).
3/3 mismatches (average diff: 0.00103)
[1] 0.1877 - 0.1871 ==  0.0006
[2] 0.0813 - 0.0801 ==  0.0012
[3] 0.0745 - 0.0758 == -0.0013
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✓ |  10       | test goodness-of-fit functions [10.1 s]

══ Results ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 21.2 s

OK:       61
Failed:   2
Warnings: 0
Skipped:  0
```

I should clarify that I'm not a statistician, so if functional changes need to be made, I will need help figuring out specifically what they are.

**Comment by Dreznel** [comment]
One more note, I believe the change in behavior from `ergm 3.10.4` to `ergm 3.11.0` stems from changes made to the `ergm::ergm(...)` function between 3.10.4 and 3.11.0. For for the failing test cases, this function is called in lines 154-161 of `mtergm.R`.

```
  if (verbose == TRUE) {
    message("Estimating...")
    e <- ergm(form, offset.coef = -Inf, constraints = constraints, 
        eval.loglik = TRUE, ...)
  } else {
    e <- suppressMessages(ergm(form, offset.coef = -Inf, 
        constraints = constraints, eval.loglik = TRUE, ...))
  }
```

I have not confirmed this, but this seems to be the only place where the the `ergm` package is being used in this function.

**Comment by dpastoor** [comment]
@leifeld thanks for chiming in - does this changeset help you close the loop on identifying the failing test issues/adjustments needed. We have 0 subject matter expertise - this is just in the dependency path of some of the packages we maintain and trying to do any cleanup possible to make it simpler to get back on track!

My immediate reaction to think potentially this is due to underlying ergm changes - perhaps in the solver, given the closeness but not exactness of the diff on the results. Perhaps @krivit would you be able to weigh in?

**Comment by leifeld** [comment]
Thanks both for your contribution! As you mentioned, the differences are small, so I'm inclined to believe it's probably due to some minor change in the MCMC or MLE routine. I'm happy to review it in more detail tomorrow afternoon and then adapt the unit tests and accept the PR if there are no further issues. Out of curiosity, what are the packages you maintain that require btergm to run? CRAN dependencies are becoming increasingly complex, which seems to have repercussions on the resilience and maintainability on the repository system.

**Comment by dpastoor** [comment]
Thanks @leifeld glad to see it start to make its way back to CRAN! To answer your question, we actually maintain a subset of CRAN, and select packages on github/internal packages, via the "metrum package network" available at: https://mpn.metworx.com/docs/ 

Its kind of like rstudio package manager as a solution, where we also build binaries, smooth out CRAN inconsistencies, build docs, and keep an eye for failures in the set of ~ 1000 packages we do include. In this case, btergm started failing thus before we got in the next snapshot we needed to remove it, which we try to not do at all cost, or see if there was a fix out there. In this case after seeing the issues posted I crossed my fingers that we could help get some of the legwork done. I absolutely appreciate how much it takes to deal with CRAN, and have had my own package pulled a couple times when dealing with other activities and know it can be hard to know just how much work it may or may not be to get back onto CRAN. As such, where we can, we try to help nudge along and help where we can when these types of situations arise.

**Comment by dpastoor** [comment]
closing as this was merged in and absorbed back to the mothership here: https://github.com/leifeld/btergm/pull/23

**Pull request closed without merging**
